accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts.views import *
from . import views

app_name = 'accounts'

urlpatterns = [
    
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<id>\d+)/edit/$', ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',ProfileDeleteView.as_view(), name="delete",),

    url(r'^login/$', auth_views.login, name='login', kwargs={'template_name': 'accounts/login_form.html'}),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': settings.LOGIN_URL}),

    url(r'^password_reset/$', views.MyPasswordResetView.as_view(), name='password_reset'),
    url(r'^reset/<uidb64>/<token>/$', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]

course/urls.py
from django.conf.urls import url
from course.views_menu import *
from course.views import *
from enrol.views import *
from . import views

app_name = 'course'

urlpatterns = [

    url(r'^$', CourseLV.as_view(), name='index'),
    url(r'^course/$', CourseLV.as_view(), name='course_list'),
    url(r'^course/(?P<pk>\d+)/$', CourseDV.as_view(), name='course_detail'),
    url(r'^add/$',CourseScheduleCV.as_view(), name="add"),
    url(r'^change/$',CourseChangeLV.as_view(), name="change",),
    url(r'^(?P<pk>[0-9]+)/update/$',CourseUpdateView.as_view(), name="update",),
    url(r'^(?P<pk>[0-9]+)/delete/$',CourseDeleteView.as_view(), name="delete",),
    url(r'^like/$', views.like, name='like'),
    url(r'^likes/$',LikesLV.as_view(), name="likes",),
    url(r'^lecturer/(?P<pk>\d+)/$', LecturerDV.as_view(), name='lecturer'),
    #url(r'^lecturer/(?P<name_pk>\d+)/$', LecturerDV.as_view(), name='lecturer'),
    
    # course_lfield_list
    url(r'^lfield/1/$', CourseL1LV.as_view(), name='course_lfield_1_list'),
    url(r'^lfield/2/$', CourseL2LV.as_view(), name='course_lfield_2_list'),
    url(r'^lfield/3/$', CourseL3LV.as_view(), name='course_lfield_3_list'),
    url(r'^lfield/4/$', CourseL4LV.as_view(), name='course_lfield_4_list'),
    url(r'^lfield/5/$', CourseL5LV.as_view(), name='course_lfield_5_list'),
    url(r'^lfield/6/$', CourseL6LV.as_view(), name='course_lfield_6_list'),
    url(r'^lfield/7/$', CourseL7LV.as_view(), name='course_lfield_7_list'),

    # course_lfield_list
    url(r'^sfield/10/$', CourseS10LV.as_view(), name='course_sfield_10_list'),
    url(r'^sfield/11/$', CourseS11LV.as_view(), name='course_sfield_11_list'),
    url(r'^sfield/12/$', CourseS12LV.as_view(), name='course_sfield_12_list'),
    url(r'^sfield/13/$', CourseS13LV.as_view(), name='course_sfield_13_list'),
    url(r'^sfield/14/$', CourseS14LV.as_view(), name='course_sfield_14_list'),
    url(r'^sfield/15/$', CourseS15LV.as_view(), name='course_sfield_15_list'),
    url(r'^sfield/16/$', CourseS16LV.as_view(), name='course_sfield_16_list'),

    url(r'^sfield/20/$', CourseS20LV.as_view(), name='course_sfield_20_list'),
    url(r'^sfield/21/$', CourseS21LV.as_view(), name='course_sfield_21_list'),
    url(r'^sfield/22/$', CourseS22LV.as_view(), name='course_sfield_22_list'),
    url(r'^sfield/23/$', CourseS23LV.as_view(), name='course_sfield_23_list'),
    url(r'^sfield/24/$', CourseS24LV.as_view(), name='course_sfield_24_list'),
    url(r'^sfield/25/$', CourseS25LV.as_view(), name='course_sfield_25_list'),

    url(r'^sfield/30/$', CourseS30LV.as_view(), name='course_sfield_30_list'),
    url(r'^sfield/31/$', CourseS31LV.as_view(), name='course_sfield_31_list'),
    url(r'^sfield/32/$', CourseS32LV.as_view(), name='course_sfield_32_list'),
    url(r'^sfield/33/$', CourseS33LV.as_view(), name='course_sfield_33_list'),
    url(r'^sfield/34/$', CourseS34LV.as_view(), name='course_sfield_34_list'),
    url(r'^sfield/35/$', CourseS35LV.as_view(), name='course_sfield_35_list'),
    url(r'^sfield/36/$', CourseS36LV.as_view(), name='course_sfield_36_list'),

    url(r'^sfield/40/$', CourseS40LV.as_view(), name='course_sfield_40_list'),
    url(r'^sfield/41/$', CourseS41LV.as_view(), name='course_sfield_41_list'),
    url(r'^sfield/42/$', CourseS42LV.as_view(), name='course_sfield_42_list'),
    url(r'^sfield/43/$', CourseS43LV.as_view(), name='course_sfield_43_list'),
    url(r'^sfield/44/$', CourseS44LV.as_view(), name='course_sfield_44_list'),
    url(r'^sfield/45/$', CourseS45LV.as_view(), name='course_sfield_45_list'),
    url(r'^sfield/46/$', CourseS46LV.as_view(), name='course_sfield_46_list'),

    url(r'^sfield/50/$', CourseS50LV.as_view(), name='course_sfield_50_list'),
    url(r'^sfield/51/$', CourseS51LV.as_view(), name='course_sfield_51_list'),
    url(r'^sfield/52/$', CourseS52LV.as_view(), name='course_sfield_52_list'),

    url(r'^sfield/60/$', CourseS60LV.as_view(), name='course_sfield_60_list'),
    url(r'^sfield/61/$', CourseS61LV.as_view(), name='course_sfield_61_list'),
    url(r'^sfield/62/$', CourseS62LV.as_view(), name='course_sfield_62_list'),
    url(r'^sfield/63/$', CourseS63LV.as_view(), name='course_sfield_63_list'),
    url(r'^sfield/64/$', CourseS64LV.as_view(), name='course_sfield_64_list'),

    url(r'^sfield/70/$', CourseS70LV.as_view(), name='course_sfield_70_list'),

]

enrol/urls.py
from django.conf.urls import url

from enrol.views import *

app_name = 'enrol'

urlpatterns = [

    url(r'^$', EnrolLV.as_view(), name='index'),
    #url(r'^enrol/(?P<pk>\d+)/$', EnrolDV.as_view(), name='enrol_detail'),
    url(r'^(?P<course_pk>\d+)/add/$',EnrolCreateView.as_view(), name="add"),
    #url(r'^change/$',EnrolChangeLV.as_view(), name="change",),
    url(r'^student/$', EnrolStudentLV.as_view(), name='enrol_student'),

]

lecturer/urls.py
from django.conf.urls import url
from lecturer.views import *

app_name = 'lecturer'

urlpatterns = [
    url(r'^$', LecturerLV.as_view(), name='index'),
    #url(r'^detail/(?P<course_pk>\d+)/$', LecturerDV.as_view(), name='lecturer'),
    url(r'^new/$',LecturerCreateView.as_view(), name="new"),
    url(r'^(?P<pk>[0-9]+)/update/$',LecturerUpdateView.as_view(), name="update",),
    url(r'^(?P<pk>[0-9]+)/delete/$',LecturerDeleteView.as_view(), name="delete",),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static # 추가
from django.conf import settings # 추가

from mysite.views import HomeView, SiteView , MypageView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView # 추가



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^$', HomeView.as_view(), name='home'), # 추가  ^$ 은 Empty string을 표현하는데, / 혹은 현재위치에 해당된다.
    url(r'^home/', SiteView.as_view(), name='sitemap'),
    url(r'^qna/', include('qna.urls', namespace='qna')),
    url(r'^accounts/mypage/$', MypageView.as_view(), name='mypage'),
    url(r'^notice/', include('notice.urls', namespace='notice')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^interest/', include('interest.urls', namespace='interest')),
    url(r'^reply/', include('reply.urls', namespace='reply')),
    url(r'^enrol/', include('enrol.urls', namespace='enrol')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),

    url(r'^password_change/', PasswordChangeView.as_view(), name='password_change', kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^password_reset/', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
 

qna/urls.py
"""from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [

    # Example: /
    url(r'^$', QnaLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^qna/$', QnaLV.as_view(), name='qna_list'),

    # Example: /album/99/
    url(r'^qna/(?P<pk>\d+)/$', QnaDV.as_view(), name='qna_detail'),

]
"""
from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [
    
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', PostDV.as_view(), name='detail'),
    url(r'^add/$',PostCreateView.as_view(), name="add",),
    url(r'^change/$',PostChangeLV.as_view(), name="change",),
    url(r'^(?P<pk>[0-9]+)/update/$',PostUpdateView.as_view(), name="update",),
    url(r'^(?P<pk>[0-9]+)/delete/$',PostDeleteView.as_view(), name="delete",),

]

accounts/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse
from django.conf import settings

from django.contrib.auth.models import User

@python_2_unicode_compatible
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    name = models.CharField('이름',max_length=50)
    tel = models.CharField('전화번호',max_length=50)
    #gender = models.BooleanField('성별',default=True)
    address = models.CharField('주소',max_length=50)
    birth = models.DateField('생년월일',auto_now=False, auto_now_add=False,null=True)
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def decade_born_in(self):
        return self.birth.strftime('%Y')[:4] # + "0's"
    decade_born_in.short_description = 'Birth decade'

    def born_in_fifties(self):
        return self.birth.strftime('%Y')[:4] == '195'
    born_in_fifties.boolean = True

class User(models.Model):
    username = models.CharField(max_length=191)
    password = models.IntegerField()
 
    def __unicode__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
 
class SignupForm(UserCreationForm):
    name = forms.CharField(max_length=50,required=False)
    tel = forms.CharField(max_length=50,required=False)
    #gender = forms.BooleanField('성별',default=True)
    address = forms.CharField(max_length=50,required=False)
    birth = forms.DateField(required=False)

    def save(self):
        user =  super().save()

        profile = Profile.objects.create(
            user = user,
            name =self.cleaned_data['name'],
            tel =self.cleaned_data['tel'],
            #gender =self.cleaned_data['gender'],
            address =self.cleaned_data['address'],
            birth =self.cleaned_data['birth'])

        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['tel', 'address']

accounts/views.py
from django.conf import settings
from django.contrib import messages #
from django.contrib.auth import login as auth_login 
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, resolve_url
from .forms import SignupForm, ProfileForm

from django.views.generic import ListView, DetailView, TemplateView
from accounts.models import Profile
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from mysite.views import LoginRequiredMixin

from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(settings.LOGIN_URL) 
    else:
        form = SignupForm()
    return render(request, 'accounts/signup_form.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

class ProfileUpdateView(UpdateView, LoginRequiredMixin):
    model = Profile
    form_class = ProfileForm
    success_url = reverse_lazy('accounts:profile')
    template_name = 'accounts/profile_change_form.html'

    def get_object(self):
        return self.request.user.profile

class ProfileDeleteView(LoginRequiredMixin, DeleteView) :
    model = Profile
    success_url = reverse_lazy('home')

    #def get_object(self):
        #return self.request.user.delete()

class MyPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/password_reset_form.html'
    
    def form_valid(self, form):
        messages.info(self.request, '암호 변경 메일을 발송했습니다.')
        return super().form_valid(form)

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/password_reset_confirm.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 리셋을 완료했습니다.')
        return super().form_valid(form)

accounts/templates/accounts/login_form.html
{% extends "base.html" %}

{% block title %}login_form{% endblock %}

<!-- {% load staticfiles %} -->
{% block content %}
<link rel="stylesheet" href="css/bootstrap.css">
	<link rel="stylesheet" href="css/hobbyist.css">
	<title>로그인</title>
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="js/bootstrap.js"></script>
	<style type="text/css">
		.btn-primary {
		    color: #ffaaaa;
		    background-color: #fff;
		    border-color: #ffaaaa;
		    
		} 
		.btn-primary:hover, .btn-primary:focus, .btn-primary.focus, .btn-primary:active, .btn-primary.active, .open > .dropdown-toggle.btn-primary {
		    color: #fff;
		    background-color: #ffaaaa;
		    border-color: #ffaaaa;
		}
		.jumbotron{
			background-color: #fff;
		}
	</style>
<div class="container">
<form action="" method="post" style="text-align: center;">
	{% csrf_token %}
	<table>
		<div class="form-row" style="display: block;">
            아이디<br>{{ form.username }}
        </div>
    
        <div class="form-row" style="display: block;">
            비밀번호<br>{{ form.password }}
        </div> 
	</table>
	<br>
	<input class="btn btn-primary form-control" style="width: 20%;" type="submit" name="로그인" value="로그인"><br><br>
	<div class="form-group text-center">
						<a href="#" tabindex="5" class="forgot-password">&nbsp;비밀번호 찾기&nbsp;&nbsp;</a><a href="{% url 'accounts:signup' %}" tabindex="5" class="register">&nbsp;&nbsp;회원가입&nbsp;&nbsp;</a>
					</div>
</form>
</div>
{% endblock %}

accounts/templates/accounts/mypage_base.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.30/css/uikit.min.css'>

<style type="text/css">
		@import url(http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css);
		.fa-fw {
			width: 2em;
		}
		.container {
			margin-left: 10px;
		}
		.nav-pills > li.active > a, .nav-pills > li.active > a:hover, .nav-pills > li.active > a:focus {
			background-color: #fff;
			color: #ffaaaa;
			font-weight: bold;
		}

		.uk-link, a {
			color: black;
		}
		.pagination>li>a, .pagination>li>span { border-radius: 50% !important;margin: 0 5px;}
	</style>
	
<!-- siedmenu -->
	<div class="container">
	    <div class="row">
	        <div class="col-md-2">
	            <ul class="nav nav-pills nav-stacked">
					{% if not user.profile.lecturer %}
	                <li class="active"><a href="{% url 'accounts:profile' %}"><i class="fa fa-cogs fa-fw"></i>기본 정보</a></li>
	                <li><a href="{% url 'enrol:index' %}"><i class="fa fa-list-alt fa-fw"></i>신청 내역</a></li>
	                <li><a href="{% url 'qna:change' %}"><i class="fa fa-file-o fa-fw"></i>문의 내역</a></li>
	                <li><a href="{% url 'course:likes' %}"><i class="fa fa-bar-chart-o fa-fw"></i>관심 내역</a></li>
					{% else %}
					<li class="active"><a href="{% url 'accounts:profile' %}"><i class="fa fa-cogs fa-fw"></i>기본 정보</a></li>
	                <li><a href="{% url 'enrol:index' %}"><i class="fa fa-list-alt fa-fw"></i>신청 내역</a></li>
	                <li><a href="{% url 'qna:change' %}"><i class="fa fa-file-o fa-fw"></i>문의 내역</a></li>
	                <li><a href="{% url 'course:likes' %}"><i class="fa fa-bar-chart-o fa-fw"></i>관심 내역</a></li>
					<li><a href="{% url 'course:add' %}"><i class="fa fa-tasks fa-fw"></i>클래스 등록</a></li>
	                <li><a href="{% url 'course:change' %}"><i class="fa fa-calendar fa-fw"></i>클래스 등록 내역</a></li>
	                <li><a href="{% url 'enrol:enrol_student' %}"><i class="fa fa-book fa-fw"></i>수강생 관리</a></li>
					<li><a href="#"><i class="fa fa-pencil fa-fw"></i>결제 관리</a></li>
					{% endif %}
	            </ul>
	        </div> 
			{% block mypage %}{% endblock mypage %}
	    </div>
	</div>
	{% endblock content %}
	

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

 {% block content %}
    <h2>새 비밀번호 입력</h2>
     <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>

{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}

 {% block content %}
    <h2>암호 리셋 요청하기</h2>
     <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
     <hr/>
     <a href="{% url 'accounts:login' %}?next={{request.path}}">로그인</a>
     
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/mypage_base.html" %}

{% block title %}mypage.html{% endblock %}
{% load staticfiles %}
{% block mypage %}
<!-- siedmenu -->
	<!-- <div class="container">
	    <div class="row"> -->
	        <div class="col-md-10 well" style="background-color: #fff;">
				<form method="POST">
					<!-- Vertical admin menu -->
	            <p><strong>아이디 : </strong>{{ user }}</p>
	            <p><strong><a href="{% url 'password_change' %}" role=button>비밀번호 변경</a></strong></p>
				<p><strong>이름 : </strong>{{ user.profile.name }}</p>
				<!-- <p><strong>성별 : </strong> 여자</p> -->
				<p><strong>전화번호 : </strong> {{ user.profile.tel }} </p>
				<p><strong>주소 : </strong> {{ user.profile.address }} </p>
				<p><strong>생년월일 : </strong> {{ user.profile.birth }} </p><br>
				<p>
					{% if user.profile.lecturer %}
					<a href="{% url 'lecturer:update' user.profile.lecturer.id %}" class="btn btn-default" role=button>강사정보변경</a>
					
					{% elif messages %}
						<a href="#" class="btn btn-default" role=button>강사신청완료</a>
						<div class="alert alert-success">
							{% for m in messages %}
							<li>{{ m }}</li>
							{% endfor %}
						</div>

					{% else %}
					<a href="{% url 'lecturer:new' %}" class="btn btn-default" role=button>강사신청</a>
					
					{% endif %}
					<a href="{% url 'accounts:profile_edit'  user.profile.id  %}" class="btn btn-default pull-right" role=button>수정하기</a>
				</p>
				</form>
	        </div>  
	    </div>
	</div>

{% endblock mypage %}

accounts/templates/accounts/profile_change_form.html
{% extends "accounts/mypage_base.html" %}

{% block title %}profile_change_form{% endblock %}

{% load staticfiles %}
{% block mypage %}
    <title>회원정보수정</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src='{% static "js/bootstrap.js" %}'></script>
    <style type="text/css">
        .btn-primary {
            color: #ffaaaa;
            background-color: #fff;
            border-color: #ffaaaa;
        }
        .btn-primary:hover, .btn-primary:focus, .btn-primary.focus, .btn-primary:active, .btn-primary.active, .open > .dropdown-toggle.btn-primary {
            color: #fff;
            background-color: #ffaaaa;
            border-color: #ffaaaa;
        }
    </style>


<!-- <div class="container"> 
    <div class="row"> -->
            
<div class="col-md-9 well" style="background-color: #fff;">
<form action="" method="post" style="text-align: center;">
    {% csrf_token %}
     <fieldset class="table table-border" style="text-align: center;">
        <table class="table table-border table-hover" style="text-align: center;">
        <thead>
            <tr>
            <th colspan="3" style="text-align: center;"><h4>회원정보수정</h4></th>
            </tr>
        </thead>
        <tbody>
        
            <tr>
                <div class="form-row">
                <td style="width: 110px;"><h5>ID</h5></td>
                <td style="text-align:left;">{{ user }}</td>
                </div>
            </tr>
            
            <tr>
            <div class="form-row">
                <td style="width: 110px;"><h5>이름</h5></td>
                <td style="text-align:left">{{ user.profile.name }}</td>        
            </div>
            </tr>
            
            <tr>
            <div class="form-row">
                <td style="width: 110px;"><h5>전화번호</h5></td>
                <td colspan="2"><input class="form-control" type="text" id="tel" name="tel" placeholder="전화번호를 입력해주세요." {{ form.tel }}</td>
            </div>
            </tr>
    
            <tr>
            <div class="form-row">
                <td style="width: 110px;"><h5>주소</h5></td>
                <td colspan="2"><input class="form-control" type="text" id="address" name="address" placeholder="주소를 입력해주세요." {{ form.address }}</td>
            </div> 
            </tr>
            
            <tr>
            <div class="form-row">
                <td style="width: 110px;"><h5>생년월일</h5></td>
                <td style="text-align:left">{{ user.profile.birth }}</td>        
            </div> 
            </tr>
            
        </tbody>
        </table>
        </fieldset>
        <br>
        <input class="btn btn-primary form-control" style="width: 20%;" type="submit" name="수정하기" value="수정하기">
        <a href="{% url 'accounts:delete'  user.profile.id  %}" class="btn btn-default" role=button>탈퇴</a>
        <a class="pull-right" href="{% url 'accounts:profile' %}" role=button>취소</a>

</form>
</div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/profile_confirm_delete.html
{% extends "accounts/mypage_base.html" %}

{% block title %}profile_confirm_delete{% endblock %}

{% block mypage %}
<!-- <div class="container">
<div class="row">  -->
<div class="col-md-9 well" style="background-color: #fff;">
<div id="content">

    <!--<h1>강사정보삭제</h1>-->

    <form action="" method="post">{% csrf_token %}
        <p>HOBBYIST를 탈퇴하시겠습니까?</p>
        <input class="btn btn-default" type="submit" value="탈퇴" />
        &nbsp;&nbsp;<a class="" href="{% url 'accounts:profile' %}" role=button>취소</a>
    </form>

</div>
</div>
</div>
</div>
{% endblock %}