course/urls.py
from django.conf.urls import url
from course.views_menu import *
from course.views import *
from enrol.views import *
from . import views

app_name = 'course'

urlpatterns = [

    url(r'^$', CourseLV.as_view(), name='index'),
    url(r'^course/$', CourseLV.as_view(), name='course_list'),
    url(r'^course/(?P<pk>\d+)/$', CourseDV.as_view(), name='course_detail'),
    url(r'^add/$',CourseScheduleCV.as_view(), name="add"),
    url(r'^change/$',CourseChangeLV.as_view(), name="change",),
    url(r'^(?P<pk>[0-9]+)/update/$',CourseUpdateView.as_view(), name="update",),
    url(r'^(?P<pk>[0-9]+)/delete/$',CourseDeleteView.as_view(), name="delete",),
    url(r'^like/$', views.like, name='like'),
    url(r'^likes/$',LikesLV.as_view(), name="likes",),
    url(r'^lecturer/(?P<pk>\d+)/$', LecturerDV.as_view(), name='lecturer'),
    #url(r'^lecturer/(?P<name_pk>\d+)/$', LecturerDV.as_view(), name='lecturer'),
    
    # course_lfield_list
    url(r'^lfield/1/$', CourseL1LV.as_view(), name='course_lfield_1_list'),
    url(r'^lfield/2/$', CourseL2LV.as_view(), name='course_lfield_2_list'),
    url(r'^lfield/3/$', CourseL3LV.as_view(), name='course_lfield_3_list'),
    url(r'^lfield/4/$', CourseL4LV.as_view(), name='course_lfield_4_list'),
    url(r'^lfield/5/$', CourseL5LV.as_view(), name='course_lfield_5_list'),
    url(r'^lfield/6/$', CourseL6LV.as_view(), name='course_lfield_6_list'),
    url(r'^lfield/7/$', CourseL7LV.as_view(), name='course_lfield_7_list'),

    # course_lfield_list
    url(r'^sfield/10/$', CourseS10LV.as_view(), name='course_sfield_10_list'),
    url(r'^sfield/11/$', CourseS11LV.as_view(), name='course_sfield_11_list'),
    url(r'^sfield/12/$', CourseS12LV.as_view(), name='course_sfield_12_list'),
    url(r'^sfield/13/$', CourseS13LV.as_view(), name='course_sfield_13_list'),
    url(r'^sfield/14/$', CourseS14LV.as_view(), name='course_sfield_14_list'),
    url(r'^sfield/15/$', CourseS15LV.as_view(), name='course_sfield_15_list'),
    url(r'^sfield/16/$', CourseS16LV.as_view(), name='course_sfield_16_list'),

    url(r'^sfield/20/$', CourseS20LV.as_view(), name='course_sfield_20_list'),
    url(r'^sfield/21/$', CourseS21LV.as_view(), name='course_sfield_21_list'),
    url(r'^sfield/22/$', CourseS22LV.as_view(), name='course_sfield_22_list'),
    url(r'^sfield/23/$', CourseS23LV.as_view(), name='course_sfield_23_list'),
    url(r'^sfield/24/$', CourseS24LV.as_view(), name='course_sfield_24_list'),
    url(r'^sfield/25/$', CourseS25LV.as_view(), name='course_sfield_25_list'),

    url(r'^sfield/30/$', CourseS30LV.as_view(), name='course_sfield_30_list'),
    url(r'^sfield/31/$', CourseS31LV.as_view(), name='course_sfield_31_list'),
    url(r'^sfield/32/$', CourseS32LV.as_view(), name='course_sfield_32_list'),
    url(r'^sfield/33/$', CourseS33LV.as_view(), name='course_sfield_33_list'),
    url(r'^sfield/34/$', CourseS34LV.as_view(), name='course_sfield_34_list'),
    url(r'^sfield/35/$', CourseS35LV.as_view(), name='course_sfield_35_list'),
    url(r'^sfield/36/$', CourseS36LV.as_view(), name='course_sfield_36_list'),

    url(r'^sfield/40/$', CourseS40LV.as_view(), name='course_sfield_40_list'),
    url(r'^sfield/41/$', CourseS41LV.as_view(), name='course_sfield_41_list'),
    url(r'^sfield/42/$', CourseS42LV.as_view(), name='course_sfield_42_list'),
    url(r'^sfield/43/$', CourseS43LV.as_view(), name='course_sfield_43_list'),
    url(r'^sfield/44/$', CourseS44LV.as_view(), name='course_sfield_44_list'),
    url(r'^sfield/45/$', CourseS45LV.as_view(), name='course_sfield_45_list'),
    url(r'^sfield/46/$', CourseS46LV.as_view(), name='course_sfield_46_list'),

    url(r'^sfield/50/$', CourseS50LV.as_view(), name='course_sfield_50_list'),
    url(r'^sfield/51/$', CourseS51LV.as_view(), name='course_sfield_51_list'),
    url(r'^sfield/52/$', CourseS52LV.as_view(), name='course_sfield_52_list'),

    url(r'^sfield/60/$', CourseS60LV.as_view(), name='course_sfield_60_list'),
    url(r'^sfield/61/$', CourseS61LV.as_view(), name='course_sfield_61_list'),
    url(r'^sfield/62/$', CourseS62LV.as_view(), name='course_sfield_62_list'),
    url(r'^sfield/63/$', CourseS63LV.as_view(), name='course_sfield_63_list'),
    url(r'^sfield/64/$', CourseS64LV.as_view(), name='course_sfield_64_list'),

    url(r'^sfield/70/$', CourseS70LV.as_view(), name='course_sfield_70_list'),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static # 추가
from django.conf import settings # 추가

from mysite.views import HomeView, SiteView , MypageView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView # 추가



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^$', HomeView.as_view(), name='home'), # 추가  ^$ 은 Empty string을 표현하는데, / 혹은 현재위치에 해당된다.
    url(r'^home/', SiteView.as_view(), name='sitemap'),
    url(r'^qna/', include('qna.urls', namespace='qna')),
    url(r'^accounts/mypage/$', MypageView.as_view(), name='mypage'),
    url(r'^notice/', include('notice.urls', namespace='notice')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^interest/', include('interest.urls', namespace='interest')),
    url(r'^reply/', include('reply.urls', namespace='reply')),
    url(r'^enrol/', include('enrol.urls', namespace='enrol')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),

    url(r'^password_change/', PasswordChangeView.as_view(), name='password_change', kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^password_reset/', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
 

qna/urls.py
"""from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [

    # Example: /
    url(r'^$', QnaLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^qna/$', QnaLV.as_view(), name='qna_list'),

    # Example: /album/99/
    url(r'^qna/(?P<pk>\d+)/$', QnaDV.as_view(), name='qna_detail'),

]
"""
from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [
    
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', PostDV.as_view(), name='detail'),
    url(r'^add/$',PostCreateView.as_view(), name="add",),
    url(r'^change/$',PostChangeLV.as_view(), name="change",),
    url(r'^(?P<pk>[0-9]+)/update/$',PostUpdateView.as_view(), name="update",),
    url(r'^(?P<pk>[0-9]+)/delete/$',PostDeleteView.as_view(), name="delete",),

]

course/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse

from course.fields import ThumbnailImageField

from accounts.models import Profile
from lecturer.models import Lecturer

@python_2_unicode_compatible
class Course(models.Model): # 강좌
    sfield = models.ForeignKey('Sfield',on_delete=models.CASCADE,null=True)
    #user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    name = models.ForeignKey(Lecturer, on_delete=models.CASCADE,null=True)
    cname = models.CharField('Cname',max_length=50)
    cost = models.IntegerField('Cost',default=0)
    startdate = models.DateField(auto_now=False, auto_now_add=False,null=True)
    enddate = models.DateField(auto_now=False, auto_now_add=False,null=True)
    minperson = models.IntegerField('최소인원',default=0)
    maxperson = models.IntegerField('최대인원',default=0)
    place = models.CharField('장소',max_length=50)
    image = ThumbnailImageField(upload_to='course/%Y/%m')
    details = models.TextField('상세정보')
    likes = models.ManyToManyField(Profile, related_name='likes')

    class Meta:
        ordering = ['-pk'] # 최근등록순

    def __str__(self):
        return self.cname

    def get_absolute_url(self):
        return reverse('course:change')

    @property
    def total_likes(self):
        return self.likes.count() #likes 컬럼의 값의 갯수를 센다

@python_2_unicode_compatible
class Gallery(models.Model): # 갤러리
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    image1 = ThumbnailImageField(upload_to='course/%Y/%m')
    image2 = ThumbnailImageField(upload_to='course/%Y/%m')
    image3 = ThumbnailImageField(upload_to='course/%Y/%m')
    image4 = ThumbnailImageField(upload_to='course/%Y/%m')
    name = models.ForeignKey(Lecturer, on_delete=models.CASCADE,null=True)

    class Meta:
        ordering = ['course']

@python_2_unicode_compatible
class Lfield(models.Model): # 대분류
    lnumber = models.IntegerField('대분류번호',null=True)
    lname = models.CharField('large field',max_length=50)

    class Meta:
        ordering = ['lnumber']
    
    def __str__(self):
        return self.lname

@python_2_unicode_compatible
class Sfield(models.Model): #소분류
    lfield = models.ForeignKey('Lfield',on_delete=models.CASCADE,null=True)
    snumber = models.IntegerField('소분류번호',null=True)
    sname = models.CharField('small field',max_length=50)

    class Meta:
        ordering = ['snumber']
    
    def __str__(self):
        return self.sname

@python_2_unicode_compatible
class Schedule(models.Model): # 일정
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    #day = models.DateField(auto_now=False, auto_now_add=False,null=True)
    starttime = models.TimeField('Starttime',auto_now=False, auto_now_add=False)
    endtime = models.TimeField('Endtime',auto_now=False, auto_now_add=False)
    name = models.ForeignKey(Lecturer, on_delete=models.CASCADE,null=True)

    class Meta:
        ordering = ['course']

    #def __str__(self): 
    #    return self.course 

    def get_absolute_url(self):
        return reverse('course:change')

course/forms.py
from course.models import Course, Schedule, Gallery
from django.forms.models import inlineformset_factory

ScheduleInlineFormSet = inlineformset_factory(Course, Schedule,
    fields = ['starttime', 'endtime'],
    extra = 1)

ScheduleUVInlineFormSet = inlineformset_factory(Course, Schedule,
    fields = ['starttime', 'endtime'],
    extra = 0)

GalleryInlineFormSet = inlineformset_factory(Course, Gallery,
    fields = ['image1', 'image2', 'image3', 'image4'],
    extra = 1)

GalleryUVInlineFormSet = inlineformset_factory(Course, Gallery,
    fields = ['image1', 'image2', 'image3', 'image4'],
    extra = 0)

course/views.py
from django.views.generic import ListView, DetailView
from course.models import Course, Schedule
from .models import Course
from lecturer.models import Lecturer
from course.forms import ScheduleInlineFormSet, ScheduleUVInlineFormSet, GalleryInlineFormSet, GalleryUVInlineFormSet

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.views.generic.base import TemplateView
from mysite.views import LoginRequiredMixin

from django.db.models import Q 
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

try:
    from django.utils import simplejson as json
except ImportError:
    import json
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse  
from django.db.models import Count

class CourseLV(ListView):
    model = Course
    paginate_by = 20

    def get_queryset(self):
        qs = Course.objects.all()
        q = self.request.GET.get('q', '')
        sort = self.request.GET.get('sort','')
        if q:
            qs = qs.filter(Q(name__name__name__icontains=q) | Q(cname__icontains=q) | Q(place__icontains=q) | Q(sfield__sname__icontains=q)).distinct()
            return qs
        elif sort == 'likes':
            course = Course.objects.annotate(like_count=Count('likes')).order_by('-like_count', '-pk')
            return course
        elif sort == 'mypost':
            user = self.request.user.profile.lecturer
            course = Course.objects.filter(name = user.id).order_by('-pk') #복수를 가져올수 있음
            return course
        elif sort == 'high_cost':
            course = Course.objects.order_by('-cost', '-pk') #복수를 가져올수 있음
            return course
        elif sort == 'low_cost':
            course = Course.objects.order_by('cost', '-pk') #복수를 가져올수 있음
            return course
        else:
            course = Course.objects.order_by('-pk')
            return course

class CourseDV(DetailView):
    model = Course

class LecturerDV(DetailView) :
    model = Course
    template_name = 'course/lecturer_detail.html'

    #def form_valid(self, form):
        #form.instance.name = get_object_or_404(Course, pk=self.kwargs['course_lecturer_pk'])
        #return super(LecturerDV, self).form_valid(form)

class CourseScheduleCV(LoginRequiredMixin, CreateView):
    model = Course
    fields = ['cname', 'cost', 'startdate', 'enddate', 'sfield', 'minperson', 'maxperson', 'place', 'image', 'details']
    
    def get_context_data(self, **kwargs):
        context = super(CourseScheduleCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = ScheduleInlineFormSet(self.request.POST, self.request.FILES)
            context['gallery_formset'] = GalleryInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = ScheduleInlineFormSet()
            context['gallery_formset'] = GalleryInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.name = self.request.user.profile.lecturer
        context = self.get_context_data()
        formset = context['formset']
        gallery_formset = context['gallery_formset']
        for scheduleform in formset:
            scheduleform.instance.name = self.request.user.profile.lecturer
        for galleryform in gallery_formset:
            galleryform.instance.name = self.request.user.profile.lecturer
        if formset.is_valid() and gallery_formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            gallery_formset.instance = self.object
            gallery_formset.save()
            return redirect('course:change')
        else:
            return self.render_to_response(self.get_context_data(form=form))

class CourseChangeLV(LoginRequiredMixin, ListView):
    template_name = 'course/course_change_list.html'
    paginate_by = 15

    def get_queryset(self):
        return Course.objects.filter(name=self.request.user.profile.lecturer)

class CourseUpdateView(LoginRequiredMixin, UpdateView) :
    model = Course
    fields = ['cname', 'cost', 'startdate', 'enddate', 'sfield', 'minperson', 'maxperson', 'place', 'image', 'details']
    template_name = 'course/course_change_form.html'
    success_url = reverse_lazy('course:change')

    def get_context_data(self, **kwargs):
        context = super(CourseUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = ScheduleUVInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
            context['gallery_formset'] = GalleryUVInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = ScheduleUVInlineFormSet(instance=self.object)
            context['gallery_formset'] = GalleryUVInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        gallery_formset = context['gallery_formset']
        if formset.is_valid() and gallery_formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            gallery_formset.instance = self.object
            gallery_formset.save()
            return redirect('course:change')
        else:
            return self.render_to_response(self.get_context_data(form=form))

class CourseDeleteView(LoginRequiredMixin, DeleteView) :
    model = Course
    success_url = reverse_lazy('course:change')

@login_required
@require_POST
def like(request):
    if request.method == 'POST':
        user = request.user.profile # 로그인한 유저를 가져온다.
        cname = request.POST.get('pk', None)
        course = Course.objects.get(pk = cname) #해당 메모 오브젝트를 가져온다.

        if course.likes.filter(id = user.id).exists(): #이미 해당 유저가 likes컬럼에 존재하면
            course.likes.remove(user) #likes 컬럼에서 해당 유저를 지운다.
            message = '좋아요 취소'
        else:
            course.likes.add(user)
            message = '좋아요 확인'+'\n'+'\n'+'[마이페이지]-[관심 내역]에서 확인하세요!'  

    context = {'likes_count' : course.total_likes, 'message' : message}
    return HttpResponse(json.dumps(context), content_type='application/json')
    # dic 형식을 json 형식으로 바꾸어 전달한다.

class LikesLV(LoginRequiredMixin, ListView):
    template_name = 'course/likes_list.html'
    paginate_by = 6

    def get_queryset(self):
        return Course.objects.filter(likes=self.request.user.profile)

course/templates/course/course_list.1.html
{% extends "base.html" %}

{% block title %}course_list{% endblock %}
{% load staticfiles %}
{% block content %}
<style> 
    input[type=text] {
        width: 275px;
        box-sizing: border-box;
        border: 2px solid #ccc;
        border-radius: 4px;
        font-size: 16px;
        background-color: white;
        background-image: url('https://images.vexels.com/media/users/3/132068/isolated/preview/f9bb81e576c1a361c61a8c08945b2c48-search-icon-by-vexels.png');
        background-size: 22px 22px;
        background-position: 10px 10px; 
        background-repeat: no-repeat;
        padding: 12px 20px 12px 40px;
        -webkit-transition: width 0.4s ease-in-out;
        transition: width 0.4s ease-in-out;
    }

    input[type=text]:focus {
        width: 100%;
    }
    </style>
    <style type="text/css">
       .btn-Success{
            border: 2px solid black;
            background-color: white;
            color: black;
            padding: 13px 25px;
            font-size: 15px;
            cursor: pointer;
            border-radius: 5px;
        }
    </style>

     <div class="container-fluid">
        <h3 class="htitle">
        <select class="form-control pull-right" name="sort-select" id="sort-select" onchange="location = this.value;" required style="width: 120px;"> 
            <option class="sort-date" value="?sort-date">최신순</option>
            <option class="sort-likes" value="?sort=likes">좋아요순</option>
            {% if user.is_authenticated %}
            <option class="sort-mypost" value="?sort=mypost">내가쓴글</option>
            {% endif %}
            <option class="sort-high_cost" value="?sort=high_cost">높은가격순</option>
            <option class="sort-low_cost" value="?sort=low_cost">낮은가격순</option>
            
            <br>


        <script type="text/javascript">
            // get url query string
            var getUrlParameter = function getUrlParameter(sParam) {
                var sPageURL = decodeURIComponent(window.location.search.substring(1)),
                    sURLVariables = sPageURL.split('&'),
                    sParameterName,
                    i;

                for (i = 0; i < sURLVariables.length; i++) {
                    sParameterName = sURLVariables[i].split('=');

                    if (sParameterName[0] === sParam) {
                        return sParameterName[1] === undefined ? true : sParameterName[1];
                    }
                }
            };
            // 정렬방식 셀렉트 박스 유지
            $(document).ready(function(){
            var sort = getUrlParameter('sort');
            if(sort == 'likes'){
                $('.sort-likes').prop('selected', 'selected')
            }else if(sort == 'mypost'){
                $('.sort-mypost').prop('selected', 'selected')
            }else if(sort == 'high_cost'){
                $('.sort-high_cost').prop('selected', 'selected')
            }else if(sort == 'low_cost'){
                $('.sort-low_cost').prop('selected', 'selected')
            }else{
                $('.sort-date').prop('selected', 'selected')
            }
            });
            </script>
        </select>
        
    </h3>
    <br>

    <style>
        .filterDiv {
          float: left;
          background-color: #ffaaaa;
          color: #ffffff;
          width: 120px;
          line-height: 70px;
          text-align: center;
          margin: 2px;
          display: none;
          font-size: 14px;
        }
        
        .show {
          display: block;
        }
        
        .container1 {
          margin-top: 20px;
          overflow: hidden;
        }
        
        /* Style the buttons */
        .btn1 {
          border: none;
          outline: none;
          padding: 12px 16px;
          background-color: #f1f1f1;
          cursor: pointer;
        }
        
        .btn1:hover {
          background-color: #ddd;
        }
        
        .btn1.active {
          background-color: #666;
          color: white;
        }
        .container1 > .filterDiv{
            cursor: pointer;
        }
        </style>


<div class="container1">
    <div class="filterDiv music" OnClick="location.href ='/course/sfield/10/'">작사/작곡</div>
    <div class="filterDiv music" OnClick="location.href ='/course/sfield/11/'">보컬/랩</div>
    <div class="filterDiv music" OnClick="location.href ='/course/sfield/12/'">피아노</div>
    <div class="filterDiv music" OnClick="location.href ='/course/sfield/13/'">기타</div>
    <div class="filterDiv music" OnClick="location.href ='/course/sfield/14/'">전통 악기</div>
    <div class="filterDiv music" OnClick="location.href ='/course/sfield/15/'">악기 기타</div>
    <div class="filterDiv music" OnClick="location.href ='/course/sfield/16/'">음악 기타</div>
</div>

<script>
filterSelection("all")
function filterSelection(c) {
  var x, i;
  x = document.getElementsByClassName("filterDiv");
  if (c == "all") c = "";
  for (i = 0; i < x.length; i++) {
    w3RemoveClass(x[i], "show");
    if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
  }
}


function w3AddClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
  }
}

function w3RemoveClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    while (arr1.indexOf(arr2[i]) > -1) {
      arr1.splice(arr1.indexOf(arr2[i]), 1);     
    }
  }
  element.className = arr1.join(" ");
}

// Add active class to the current button (highlight it)
var btnContainer = document.getElementById("myBtnContainer");
var btns = btnContainer.getElementsByClassName("nav-item");
for (var i = 0; i < btns.length; i++) {
  btns[i].addEventListener("click", function(){
    var current = document.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    this.className += " active";
  });
}
</script>





        <hr>
        <p>
            <form action="" method="get">
                <input type="text" name="q" placeholder="검색어를 입력해주세요." value="{{ q }}" />
            </form>
        </p>
        {% if object_list %}
        <div class=bs-example data-example-id=thumbnails-with-custom-content > 
            <div class=row> 
                {% for course in object_list %}
                <div class="col-sm-4 col-md-3"> 
                    <div class=thumbnail> <img src="{{ course.image.thumb_url }}" >
                     
                        <div class=caption> 
                            <h5>{{ course.cname|slice:":13" }}</h5> 
                            <br>
                            <p>강사명; {{ course.name }}</p> 
                            <p>장소; {{ course.place|slice:":18" }}</p>
                            <p>가격; {{ course.cost }}원</p>
                            <p><br>
                                <a href="{% url 'course:lecturer' course.pk %}" class="btn btn-primary" role=button>강사소개</a>
                                <a href="{% url 'course:course_detail' course.id %}" class="btn btn-default" role=button>자세히</a>
                            </p> 
                        </div> 
                        
                    </div> 
                </div>
                {% endfor %}               
            </div>

            {% elif sort == 'likes' %}
            <div class=row>
            {% for course in object_list %}
                <div class="col-sm-4 col-md-3"> 
                    <div class=thumbnail> <img src="{{ course.image.thumb_url }}" >
                     
                        <div class=caption> 
                            <h4>{{ course.cname }}</h4> 
                            <br>
                            <p>강사명; {{ course.name }}</p> 
                            <p>장소; {{ course.place }}</p>
                            <p>가격; {{ course.cost }}원</p>
                            <p><br>
                                <a href="{% url 'lecturer:lecturer' course.id %}" class="btn btn-primary" role=button>강사소개</a>
                                <a href="{% url 'course:course_detail' course.id %}" class="btn btn-default" role=button>자세히</a>
                                <a style="color: #000000;">♥{{ like_count }}</a>
                            </p> 
                        </div> 
                        
                    </div> 
                </div>
                {% endfor %}
            </div>
            
            
            {% elif not object_list %}
            <b><i>"{{ q }}"를 찾을 수 없습니다.</i></b>
            {% endif %}
        
            <div class="text-center">
                {% if is_paginated %}
                <ul class="pagination" style="display: inline-block">
                  {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                  {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                  {% endif %}
                  {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                      <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                  {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                  {% endif %}
                </ul>
                {% endif %}
                </div>
        </div>       
    </div>
{% endblock %}    