mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static # 추가
from django.conf import settings # 추가

from mysite.views import HomeView, SiteView , MypageView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView # 추가



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^$', HomeView.as_view(), name='home'), # 추가  ^$ 은 Empty string을 표현하는데, / 혹은 현재위치에 해당된다.
    url(r'^home/', SiteView.as_view(), name='sitemap'),
    url(r'^qna/', include('qna.urls', namespace='qna')),
    url(r'^accounts/mypage/$', MypageView.as_view(), name='mypage'),
    url(r'^notice/', include('notice.urls', namespace='notice')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^interest/', include('interest.urls', namespace='interest')),
    url(r'^reply/', include('reply.urls', namespace='reply')),
    url(r'^enrol/', include('enrol.urls', namespace='enrol')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),

    url(r'^password_change/', PasswordChangeView.as_view(), name='password_change', kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^password_reset/', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
 

qna/urls.py
"""from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [

    # Example: /
    url(r'^$', QnaLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^qna/$', QnaLV.as_view(), name='qna_list'),

    # Example: /album/99/
    url(r'^qna/(?P<pk>\d+)/$', QnaDV.as_view(), name='qna_detail'),

]
"""
from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [
    
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', PostDV.as_view(), name='detail'),
    url(r'^add/$',PostCreateView.as_view(), name="add",),
    url(r'^change/$',PostChangeLV.as_view(), name="change",),
    url(r'^(?P<pk>[0-9]+)/update/$',PostUpdateView.as_view(), name="update",),
    url(r'^(?P<pk>[0-9]+)/delete/$',PostDeleteView.as_view(), name="delete",),

]

qna/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

@python_2_unicode_compatible
class Qna(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('제목',max_length=50,null=True)
    createdate = models.DateTimeField('생성일자',auto_now_add=True, null=True)
    modifydate = models.DateTimeField('수정일자',auto_now=True,null=True)
    details = models.TextField('내용')

    class Meta:
        ordering = ['-pk'] # 최근등록순

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail')

    #def createdate_in(self):
    #    return self.createdate.strftime('%Y-%m-%d %H:%M')
    #createdate_in.short_description = 'createdate decade'

    
    

qna/views.py
"""#from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView, DetailView
from qna.models import Qna

# Create your views here.

class QnaLV(ListView):
    model = Qna

class QnaDV(DetailView):
    model = Qna


class PostLV(ListView) :
    model = Qna
    template_name = 'qna/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2
"""
from django.shortcuts import render

from django.views.generic import ListView, DetailView, TemplateView

from qna.models import Qna

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.

#--- ListView
class PostLV(ListView) :
    model = Qna
    paginate_by = 15
    #context_object_name = 'posts'

#--- DetailView
class PostDV(DetailView) :
    model = Qna

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Qna
    fields = ['title', 'details']
    success_url = reverse_lazy('qna:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'qna/qna_change_list.html'
    paginate_by = 15

    def get_queryset(self):
        return Qna.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView) :
    model = Qna
    fields = ['title', 'details']
    success_url = reverse_lazy('qna:index')

class PostDeleteView(LoginRequiredMixin, DeleteView) :
    model = Qna
    success_url = reverse_lazy('qna:index')

qna/templates/qna/qna_change_list.html
{% extends "accounts/mypage_base.html" %}

{% block title %}qna_change_list{% endblock %}

{% block mypage %}
	
<!-- siedmenu -->
	<!-- <div class="container">
	    <div class="row"> -->
	        
	        <div class="col-md-10 well" style="background-color: #fff;">
	            <!-- <div class="container"> -->
	            <table class="table table-hover">
	              <thead>
	              	<tbody>
	                <tr>
	                  <th scope="col">제목</th>
                  <th scope="col">작성일자</th>
                  <th scope="col">수정일자</th>
                  <th scope="col">작성자</th>
                  <th scope="col">수정</th>
                  <th scope="col">삭제</th>
	                </tr>
	            	</tbody>
	              </thead>
	              {% for item in object_list %}
              <tbody>
                <tr>
                  <th scope="row">{{ item.title }}</th>
                  <td>{{ item.createdate|date:"Y년 N d일" }}</td>
                  <td>{{ item.modifydate|date:"Y년 N d일" }}</td>
                  <td>{{ item.owner }}</td>
                  <td><a href="{% url 'qna:update' item.id %}">수정</a></td>
                  <td><a href="{% url 'qna:delete' item.id %}">삭제</a></td>
                </tr>
              </tbody>
              {% endfor %}
	            </table>
	            <div class="text-center">
									{% if is_paginated %}
									<ul class="pagination" style="display: inline-block">
										{% if page_obj.has_previous %}
											<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
										{% else %}
											<li class="disabled"><span>&laquo;</span></li>
										{% endif %}
										{% for i in paginator.page_range %}
											{% if page_obj.number == i %}
												<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
											{% else %}
												<li><a href="?page={{ i }}">{{ i }}</a></li>
											{% endif %}
										{% endfor %}
										{% if page_obj.has_next %}
											<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
										{% else %}
											<li class="disabled"><span>&raquo;</span></li>
										{% endif %}
									</ul>
									{% endif %}
									</div>
	            </div>
	        </div> 
			
	    </div>
	</div>
{% endblock %}

qna/templates/qna/qna_confirm_delete.html
{% extends "accounts/mypage_base.html" %}

{% block title %}qna_confirm_delete{% endblock %}

{% block mypage %}
<div class="container">
	<div class="row">
            
<div class="col-md-9 well" style="background-color: #fff;">
<div id="content">

    <h1>Post Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
</div>
</div>
</div>
{% endblock %}

qna/templates/qna/qna_detail.html
{% extends "base.html" %}

{% block title %}qna_detail{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-12">
    
        <h4>{{ qna.title }}</h4><br>
        <p>{{ qna.details }}<br></p>
    
        <span class="badge">수정일자 {{ qna.modifydate }}</span>
        <span class="label label-default pull-right">
            <a href="{% url 'qna:index' %}" style="color: white;">목록</a>
        </span>
    
        <br/><br/>
        <div>
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
    
    </div>
    </div>
{% endblock %}

qna/templates/qna/qna_form.html
{% extends "base.html" %}

{% block title %}qna_form{% endblock %}

{% load staticfiles %}
<!-- {% block extrastyle %}{% static "css/forms.css" %}{% endblock %} -->

{% block content %}
<link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/hobbyist.css">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <style type="text/css">
        .btn-primary {
            color: #ffaaaa;
            background-color: #fff;
            border-color: #ffaaaa;
        }
        .btn-primary:hover, .btn-primary:focus, .btn-primary.focus, .btn-primary:active, .btn-primary.active, .open > .dropdown-toggle.btn-primary {
            color: #fff;
            background-color: #ffaaaa;
            border-color: #ffaaaa;
        }

        .form-control, .textarea {
            display: block;
            width: 100%;
            height: 34px;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857143;
            color: #555;
            background-color: #fff;
            background-image: none;
            border: 1px solid #ccc;
            border-radius: 4px;
            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
            -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
            -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        }
    </style>


<div class="container">

    <!-- <h1> QNA 문의사항 {{user}}</h1> -->

    <form action="#" method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}


    <fieldset class="table table-border" style="text-align: center;">
        <thead>
                    <tr>
                        <th colspan="3" style="text-align: center;"><h4>Q&A</h4></th>
                    </tr>
                </thead>

       <!--  <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div> -->
        <div class="form-row">
        <P><td colspan="2"><input class="form-control" type="text" id="title" name="title" maxlength="30" placeholder="제목을 입력해주세요." {{ form.title }}</td></P>
        </div>
    
        <div class="form-row">
            <!-- {{ form.tag.label_tag }} --> 
            <td><textarea class="textarea" style="width: 100%; height: 300px;" placeholder="내용을 입력해주세요." {{ form.details }}</textarea>
            </td>
        </div>

    </fieldset>

    <!-- <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div> -->
    <tr>
        <td style="text-align: left;" colspan="3"><input class="btn btn-primary pull-right" type="submit" name="문의하기" value="문의하기"></td>
    </tr>
    
    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

qna/templates/qna/qna_list.html
{% extends "base.html" %}

{% block title %}qna_list{% endblock %}

{% block content %}	
	<!-- tap -->
	<div class="container">
		
		<div class="row">
		<div>

	  <!-- Nav tabs -->
	  <ul class="nav nav-tabs" role="tablist">
	    <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab" data-toggle="tab">Q&amp;A</a></li>
	  </ul>

	  <!-- Tab panes -->
	  <div class="tab-content" style="width: 1000px;">
	    <div role="tabpanel" class="tab-pane active" id="notice">
	    	<!-- 공지 -->
	    	<br>
	    	<div class="container">
	    	<table class="table table-hover">
	    	  <thead>
	    	  	<tbody>
	    	    <tr>
	    	      <th scope="col">#</th>
	    	      <th scope="col">제목</th>
	    	      <th scope="col">작성자</th>
	    	      <th scope="col">작성일자</th>
	    	    </tr>
	    		</tbody>
	    	  </thead>
	    	  {% for qna in object_list %}
	    	  <tbody>
	    	    <tr>
	    	      <th scope="row">{{ qna.id }}</th>
	    	      <td><a href="{% url 'qna:detail' qna.id %}">{{ qna.title }}</a></td>
	    	      <td>{{ qna.owner }}</td>
	    	      <td>{{ qna.createdate|date:"Y-n-d H:m:s" }}</td>
	    	    </tr>
	    	  </tbody>
	    	  {% endfor %}
	    	</table>
	    	<div class="text-center">
					{% if is_paginated %}
					<ul class="pagination" style="display: inline-block">
						{% if page_obj.has_previous %}
							<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
						{% else %}
							<li class="disabled"><span>&laquo;</span></li>
						{% endif %}
						{% for i in paginator.page_range %}
							{% if page_obj.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
							{% else %}
								<li><a href="?page={{ i }}">{{ i }}</a></li>
							{% endif %}
						{% endfor %}
						{% if page_obj.has_next %}
							<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
						{% else %}
							<li class="disabled"><span>&raquo;</span></li>
						{% endif %}
					</ul>
					{% endif %}
					</div>
	    	</div>
	    </div>

	    	<div class="text-center">
	    		<ul class="pagination">
	    			<li><a href="{% url 'qna:add' %}">글쓰기</a></li>
	    		</ul>
	    	</div>
	    </div>

	  </div>
	</div>
	</div>
	
	</div>
{% endblock %}