accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts.views import *
from . import views

app_name = 'accounts'

urlpatterns = [
    
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<id>\d+)/edit/$', ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',ProfileDeleteView.as_view(), name="delete",),

    url(r'^login/$', auth_views.login, name='login', kwargs={'template_name': 'accounts/login_form.html'}),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': settings.LOGIN_URL}),

    url(r'^password_reset/$', views.MyPasswordResetView.as_view(), name='password_reset'),
    url(r'^reset/<uidb64>/<token>/$', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static # 추가
from django.conf import settings # 추가

from mysite.views import HomeView, SiteView , MypageView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView # 추가



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^$', HomeView.as_view(), name='home'), # 추가  ^$ 은 Empty string을 표현하는데, / 혹은 현재위치에 해당된다.
    url(r'^home/', SiteView.as_view(), name='sitemap'),
    url(r'^qna/', include('qna.urls', namespace='qna')),
    url(r'^accounts/mypage/$', MypageView.as_view(), name='mypage'),
    url(r'^notice/', include('notice.urls', namespace='notice')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^interest/', include('interest.urls', namespace='interest')),
    url(r'^reply/', include('reply.urls', namespace='reply')),
    url(r'^enrol/', include('enrol.urls', namespace='enrol')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),

    url(r'^password_change/', PasswordChangeView.as_view(), name='password_change', kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^password_reset/', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
 

qna/urls.py
"""from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [

    # Example: /
    url(r'^$', QnaLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^qna/$', QnaLV.as_view(), name='qna_list'),

    # Example: /album/99/
    url(r'^qna/(?P<pk>\d+)/$', QnaDV.as_view(), name='qna_detail'),

]
"""
from django.conf.urls import url

from qna.views import *

app_name = 'qna'

urlpatterns = [
    
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', PostDV.as_view(), name='detail'),
    url(r'^add/$',PostCreateView.as_view(), name="add",),
    url(r'^change/$',PostChangeLV.as_view(), name="change",),
    url(r'^(?P<pk>[0-9]+)/update/$',PostUpdateView.as_view(), name="update",),
    url(r'^(?P<pk>[0-9]+)/delete/$',PostDeleteView.as_view(), name="delete",),

]

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viweport" content="width=device-width", initial-scale="1">
	<title>{% block title %}hobbyist{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href='{% static "css/hobbyist.css" %}'>
<link rel="stylesheet" type="text/css" href='{% static "css/bootstrap.css" %}'>


<link href='{% static "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" %}' rel="stylesheet" id="bootstrap-css">
<script src='{% static "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js" %}'></script>
<script src='{% static "//code.jquery.com/jquery-1.11.1.min.js" %}'></script>

<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js"></script>
<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-animate.js"></script>
<script language="javascript" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.14.3.js"></script>

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

	  <!-- Bootstrap core CSS -->
	  <link rel="stylesheet" type="text/css" href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}'>

	  <!-- Custom fonts for this template -->
	  <link rel="stylesheet" type="text/css" href='{% static "vendor/fontawesome-free/css/all.min.css" %}'>
	  <link href='{% static "//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" %}' rel="stylesheet" type="text/css">
	<link href='{% static "//fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" %}' rel="stylesheet" type="text/css">

	  <!-- Plugin CSS -->
	  <link rel="stylesheet" type="text/css" href='{% static "vendor/magnific-popup/magnific-popup.css" %}'>

	  <!-- Custom styles for this template -->
	  <link href='{% static "css/creative.min.css" %}' rel="stylesheet" type="text/css">

	 <style type="text/css">
	 .dropdown-menu{
	  border: 0px;
	 }
	 /*a.dropdown-toggle{
	  color: #f8f9fa!important;
	 }*/
	  ul.nav-item.dropdown-menu.show{
	    background-color: transparent;
	    left: 15px;
	    
	  }
	  /*ul.nav-item.dropdown-toggle{
	    padding-top: 20px;
	  }*/
	  ul.nav-item.dropdown-menu>li>a{
	    color: black;
	  }
	  ul.nav-item.dropdown-menu>li>a:hover{
	    color: #ffaaaa;
	    text-decoration: none;
	}
	/*li.nav-item.dropdown>a.dropdown-toggle{
	  color: #f8f9fa;
	}*/
	  li.nav-item.dropdown>a.dropdown-toggle:hover{
	  text-decoration: none;
	  }
	 </style>
	 <style type="text/css">
	  #mainNav .navbar-nav > li.dropdown > a.dropdown-toggle, #mainNav .navbar-nav > li.dropdown > a.dropdown-toggle:focus, #mainNav .navbar-nav>li.nav-item>a.nav-link, #mainNav .navbar-nav>li.nav-item>a.nav-link:focus {
	    color: black;
	    font-size: 15px;
	    font-weight: bold;
	    font-family: 'Merriweather', 'Helvetica Neue', Arial, sans-serif;
	  }
	  #dropdown-toggle:hover {
	    color: #ffaaaa;
	  }
	  body {
	    font-family: 'Merriweather', 'Helvetica Neue', Arial, sans-serif;
	  }
	 </style>


	<style type="text/css">
		.btn-group-primary {
			background-color: #ffaaaa; 
		}
		.btn-group .dropdown-menu a{
		    color:black;
		}
		.btn-group-default .dropdown-menu {
		  background-color: #fff !important;
		}
		.btn-group-default .dropdown-menu li > a:hover,
		.btn-group-default .dropdown-menu li > a:focus {
		  color: #fff;
		  background-color: #FFaaaa !important;
		}
	</style>
	

	<style type="text/css">
		.jumbotron{
			background-image: url('images/main.jpg');
			background-size: cover;
			color: white;
		}
		.btn-primary {
		    color: #fff;
		    background-color: #ffaaaa;
		    border-color: #ffaaaa;
		    border-bottom-color: #ffaaaa;
		    border-top-color: #ffaaaa;
		    border-right-color: #ffaaaa;
		    border-left-color: #ffaaaa;
		}
		.btn-primary:hover {
		    color: #fff;
		    background-color: #FF9090;
		    border-color: #FF9090;
		    border-bottom-color: #FF9090;
		    border-top-color: #FF9090;
		    border-right-color: #FF9090;
		    border-left-color: #FF9090;
		}
	</style>
	<style type="text/css">
		.panel-primary > .panel-heading {
		    color: #fff;
		    background-color: ffaaaa;
		    border-color: ffaaaa;
		}
	</style>

	<!-- grid -->

	<style type="text/css">
	.new-deal{
		width:100%; 
		float:left; 
		padding:15px 0;
	}
/*	ul {
		margin:20px auto;
		width:40%;
	}
	ul li {
		display: inline-block;
		list-style: none;
		margin:0;
	}*/
	.demoFirst {
		position:relative;
		width:340px;
		height:200px;
		overflow:hidden;
		float:left;
		margin-right:20px;
		background-color:rgba(255, 170, 170, 100);
	}
	.demoFirst p,.demoFirst h2 {
		color:#fff;
		padding:10px;
		left:-20px;
		top:20px;
		position:relative
	}
	.demoFirst p {
		font-size:12px;
		line-height:18px;
		margin:0
	}
	.demoFirst h2 {
		font-size:20px;
		line-height:24px;
		margin:0;
	}
	.effect img {
		position:absolute;
		left:0;
		bottom:0;
		cursor:pointer;
		width: 100%;
		-webkit-transition:bottom .3s ease-in-out;
		-moz-transition:bottom .3s ease-in-out;
		-o-transition:bottom .3s ease-in-out;
		transition:bottom .3s ease-in-out;
	}
	.effect img.top:hover {
		bottom:-96px;
		padding-top:100px;
	}
	h2.zero,p.zero {
		margin:0;
		padding:0
	}

	.col-md-6 {
		padding-right: 90px;
		padding-left: 50px;
	}
	</style>

	</style>
	<style type="text/css">
		#myBtn {
		    display: none; /* Hidden by default */
		    position: fixed; /* Fixed/sticky position */
		    bottom: 20px; /* Place the button at the bottom of the page */
		    right: 30px; /* Place the button 30px from the right */
		    z-index: 99; /* Make sure it does not overlap */
		    border: none; /* Remove borders */
		    outline: none; /* Remove outline */
		    background-color: #ffaaaa; /* Set a background color */
		    color: white; /* Text color */
		    cursor: pointer; /* Add a mouse pointer on hover */
		    padding: 15px; /* Some padding */
		    border-radius: 10px; /* Rounded corners */
		    font-size: 18px; /* Increase font size */
		}

		#myBtn:hover {
		    background-color: #ff9090; /* Add a dark-grey background on hover */
		}
	</style>

</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}"><img src="{% static 'img/logo.gif' %}" style="height: 50px;"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto" id="myBtnContainer">
            <li class="nav-item active" onclick="filterSelection('all')">
              <a class="nav-link js-scroll-trigger" href="{% url 'course:index' %}">All</a>
            </li>
            <li class="nav-item" onclick="filterSelection('music')">
              <a class="nav-link js-scroll-trigger" href="/course/lfield/1/">MUSIC</a>
            </li>
            <li class="nav-item" onclick="filterSelection('arts')">
              <a class="nav-link js-scroll-trigger" href="/course/lfield/2/">ARTS</a>
            </li>
            <li class="nav-item" onclick="filterSelection('sports')">
              <a class="nav-link js-scroll-trigger" href="/course/lfield/3/">SPORTS</a>
            </li>
            <li class="nav-item" onclick="filterSelection('food')">
              <a class="nav-link js-scroll-trigger" href="/course/lfield/4/">FOOD</a>
            </li>
            <li class="nav-item" onclick="filterSelection('digitals')">
              <a class="nav-link js-scroll-trigger" href="/course/lfield/5/">DIGITALS</a>
            </li>
            <li class="nav-item" onclick="filterSelection('beauty')">
              <a class="nav-link js-scroll-trigger" href="/course/lfield/6/">BEAUTY</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/course/lfield/7/">ETC</a>
            </li>

            <li class="nav-item dropdown" style="padding-top: 6.5px;">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: #ffaaaa;">Join <!-- <b class="caret"></b> --></a>
              <ul class="nav-item dropdown-menu">
                {% if not user.is_active %}
                <li><a href="{% url 'accounts:login' %}?next={{request.path}}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sgin up</a></li>
                {% else %}
                <li><a href="{% url 'accounts:profile' %}">My page</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                {% endif %}
              </ul>
            </li> 

          </ul>
        </div>
      </div>
    </nav>

	  {% block content %}{% endblock %}

	<!-- 탑버튼 -->
	<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

	<!--modal-->
	   <div class="row">
	      <div class="modal" id="modal" tabindex="-1">
	         <div class="modal-dialog">
	            <div class="modal-content">
	               <div class="modal-header">
	                  하비스트 소개
	                  <button class="close" data-dismiss="modal">&times;</button>
	               </div>
	               <div class="modal-body" style="text-align: center;">
	                  특징<br>
	                  하비스트는 SNS나 개인 홈페이지를 통해 확인할 수 있는<br>
	                  원데이 클래스를 모아서 분야별로 쉽게 보여주는 사이트입니다.<br><br>
	                  <img src="{% static 'img/logo.gif' %}" id="imagepreview" style="width: 300px;"> <br>
	                  <a href="{% url 'sitemap' %}">사이트맵</a>
	               </div>
	            </div>
	         </div>
	      </div>
	   </div>
	   <!--modal-->   
	   <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	   <script src="js/bootstrap.js"></script>
	   <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	   <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	   <script language="javascript">
	       angular.module('myApp', ['ngAnimate', 'ui.bootstrap']);
	       angular.module('myApp').controller('myCntrl', function ($scope) {
	           $scope.today = function () {
	               $scope.dt = new Date();
	           };
	           $scope.mindate = new Date();
	           $scope.dateformat="MM/dd/yyyy";
	           $scope.today();
	           $scope.showcalendar = function ($event) {
	               $scope.showdp = true;
	           };
	           $scope.showdp = false;
	       });
	   </script>
	   
	   

	<script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
  <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
  <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/creative.min.js"></script>


	<script type="text/javascript">
		// When the user scrolls down 20px from the top of the document, show the button
		window.onscroll = function() {scrollFunction()};

		function scrollFunction() {
		    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
		        document.getElementById("myBtn").style.display = "block";
		    } else {
		        document.getElementById("myBtn").style.display = "none";
		    }
		}

		// When the user clicks on the button, scroll to the top of the document
		function topFunction() {
		    document.body.scrollTop = 0; // For Safari
		    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
		}
	</script>
	
<br>
<br>
<br>
<br>
<br>
<br>
	{% block footer %}
	<footer style="background-color: white; color: black;">
		<div class="container">
			<br>
			<div class="row">
				<div class="col-sm-10" style="text-align: center;"><h5>Copyright &copy; 2018 </h5><h5>취미 그 이상, 하비스트(HOBBYIST)</h5><!--<h4>대표자소개</h4>--><p>한양여자대학교 정보경영과 3-A 전미정 정문희 정지수</p></div>
				
				<div class="col-sm-2">
					<div class="list-group">
						<a data-target="#modal" data-toggle="modal" class="list-group-item" >사이트 소개</a>
						<a href="{% url 'notice:index' %}" class="list-group-item">공지사항</a>
						<a href="{% url 'qna:index' %}" class="list-group-item">문의</a>
					</div>
				</div>
				</div>
				
			</div>
		</div>
	</footer>
	{% endblock footer %}
	
</body>
</html>

templates/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
        {% if page.has_next %}
          <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
  </div>

templates/sitemap.html
{% extends "base.html" %}

{% block title %}sitemap.html{% endblock %}
{% load staticfiles %}
{% block content %}
<!-- 사이트맵 -->
<style type="text/css">
		body, html, div {
		    font-family: 'nanumgothic', 'Nanum Gothic', '나눔 고딕';
		    margin: auto;
		    
		    font-smoothing: antialiased;
		    -webkit-font-smoothing: antialiased;
		    -moz-osx-font-smoothing: grayscale;
		}

		a:link {
		    text-decoration: none;
		    color: #252525;
		}

		a:visited {
		    text-decoration: none;
		    color: #252525;
		}

		a:hover {
		    text-decoration: none;
		    color: #252525;
		}

		a:active {
		    text-decoration: none;
		    color: #252525;
		}

	</style>
	<style type="text/css">
		#sitemap>ul{display:table;table-layout:fixed;width:104%;margin-left:-4%}
		#sitemap>ul+ul{margin-top:40px}
		#sitemap>ul>li{
			display:table-cell;
			padding-left:4%
		}
		#sitemap>ul>li>a{
			display:block;
			padding:10px 15px;
			border-top:1px solid #ffaaaa;border-bottom:1px solid #FFC6C6;
			font-size:18px;font-weight:600;color:#ff9090;letter-spacing:-1px;line-height:1.2em
		}
		#sitemap>ul>li:hover>a{
			background:#ffaaaa; /*url(../img/etc/sitemap_bg.png) no-repeat right center;*/
			color:#fff
		}
		#sitemap>ul>li>ul>li{
			border-top:1px solid #eee;
			padding:12px 15px 10px;
		}
		#sitemap>ul>li>ul>li:first-child{border-top:0}
		#sitemap>ul>li>ul>li>a{
			font-size:15px;font-weight:600;color:#666;letter-spacing:-1px;line-height:1.1em
		}
		#sitemap>ul>li>ul>li:hover>a{color:#ffaaaa}
		#sitemap>ul>li>ul ul{padding:10px 0 0 5px}
		#sitemap>ul>li>ul ul li{
			padding:0 0 5px 12px;
			/*background:url(../img/etc/sitemap_dot.png) no-repeat 0 6px;*/
		}
		#sitemap>ul>li>ul ul li a{font-size:13px;color:#666;letter-spacing:-1px}
		#sitemap>ul>li>ul ul li a:hover{color:#ff9090;text-decoration:underline}
		/*#top>span a.sitemap{background-image:url(../img/common/top4.png)}*/
	</style>
</head>
<body>
	<script type="text/javascript">

	    title="사이트맵";

	</script>
	<article>
	    <div id="sitemap">
	  <ul>
	    <li>
	      <a href="#">메뉴</a>
	      <ul id="sitemap_721">
	        <li>
	          <a href="{% url 'course:index' %}">전체</a>
	        </li>
	        <li>
	          <a href="category.html?categoryName=music">음악</a>
	          <ul id="sitemap_726">
	            <li><a href="category.html?categoryName=music">작사/작곡</a></li>
	            <li><a href="category.html?categoryName=music">보컬/랩</a></li>
	            <li><a href="category.html?categoryName=music">피아노</a></li>
	            <li><a href="category.html?categoryName=music">기타</a></li>
	            <li><a href="category.html?categoryName=music">전통 악기</a></li>
	            <li><a href="category.html?categoryName=music">악기 기타</a></li>
	            <li><a href="category.html?categoryName=music">음악 기타</a></li>
	          </ul>
	        </li>
	        <li><a href="category.html?categoryName=art">미술</a>
	        	<ul>
	        		<li><a href="category.html?categoryName=art">공예</a></li>
	        		<li><a href="category.html?categoryName=art">회화</a></li>
	        		<li><a href="category.html?categoryName=art">만화</a></li>
	        		<li><a href="category.html?categoryName=art">캘리그라피</a></li>
	        		<li><a href="category.html?categoryName=art">디자인</a></li>
	        		<li><a href="category.html?categoryName=art">미술 기타</a></li>
	        	</ul>
	        </li>
	        <li><a href="category.html?categoryName=sports">운동</a>
	        	<ul>
	        		<li><a href="category.html?categoryName=sports">댄스</a></li>
	        		<li><a href="category.html?categoryName=sports">요가</a></li>
	        		<li><a href="category.html?categoryName=sports">홈트레이닝</a></li>
	        		<li><a href="category.html?categoryName=sports">필라테스</a></li>
	        		<li><a href="category.html?categoryName=sports">수영</a></li>
	        		<li><a href="category.html?categoryName=sports">스케이트/보드</a></li>
	        		<li><a href="category.html?categoryName=sports">운동 기타</a></li>
	        	</ul>
	        </li>
	        <li><a href="category.html?categoryName=food">푸드</a>
	        	<ul>
	        		<li><a href="category.html?categoryName=food">한식</a></li>
	        		<li><a href="category.html?categoryName=food">양식</a></li>
	        		<li><a href="category.html?categoryName=food">일/중식</a></li>
	        		<li><a href="category.html?categoryName=food">해외 음식</a></li>
	        		<li><a href="category.html?categoryName=food">베이킹/디저트</a></li>
	        		<li><a href="category.html?categoryName=food">바리스타</a></li>
	        		<li><a href="category.html?categoryName=food">푸드 기타</a></li>
	        	</ul>
	        </li>
	        <li><a href="category.html?categoryName=digital">디지털</a>
	        	<ul>
	        		<li><a href="category.html?categoryName=digital">컴퓨터/프로그래밍</a></li>
	        		<li><a href="category.html?categoryName=digital">카메라/사진</a></li>
	        		<li><a href="category.html?categoryName=digital">디지털 기타</a></li>
	        	</ul>
	        </li>
	        <li><a href="category.html?categoryName=beauty">뷰티</a>
	        	<ul>
	        		<li><a href="category.html?categoryName=beauty">헤어</a></li>
	        		<li><a href="category.html?categoryName=beauty">메이크업</a></li>
	        		<li><a href="category.html?categoryName=beauty">네일아트</a></li>
	        		<li><a href="category.html?categoryName=beauty">피부관리</a></li>
	        		<li><a href="category.html?categoryName=beauty">뷰티 기타</a></li>
	        	</ul>
	        </li>
	        <li><a href="category.html?categoryName=ect">기타</a></li>
	      </ul>
	    </li>
	    <li>
	      <a href="{% url 'notice:index' %}">공지사항</a>
	        <ul>
	        	<li><a href="{% url 'notice:index' %}">공지사항</a></li>
	        	<li><a href="faq.html">FAQ</a></li>
	        	<li><a href="{% url 'qna:index' %}">Q&amp;A</a>
	        	</li>
	        </ul>
	    </li>
	    <li>
	      <a href="{% url 'mypage' %}">마이페이지</a>
	      <ul>
	        <li><a href="{% url 'mypage' %}">기본 정보</a></li>
	        <li><a href="{% url 'enrol:index' %}">신청 내역</a></li>
	        <li><a href="{% url 'qna:change' %}">문의 내역</a></li>
	        <li><a href="{% url 'interest:index' %}">관심 내역</a></li>
	        <li><a href="{% url 'reply:index' %}">댓글 내역</a></li>
	        <li><a href="#">(강사)클래스 등록</a></li>
	        <li><a href="#">(강사)클래스 등록 내역</a></li>
	        <li><a href="#">(강사)수강생 관리</a></li>
	        <li><a href="#">(강사)결제 관리</a></li>
	      </ul>
	    </li>
	    <li>
	      <a href="#">접속</a>
	      <ul>
	        <li><a href="{% url 'accounts:login' %}">로그인</a></li>
	        <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
	      </ul>
	    </li>
	  </ul>
	</div>


	</article>
{% endblock %}    